# ========= Copyright 2023-2024 @ CAMEL-AI.org. All Rights Reserved. =========
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========= Copyright 2023-2024 @ CAMEL-AI.org. All Rights Reserved. =========

"""Autonomous review pipeline.

Pipeline stages:
1. Planning: LLM analyzes input and returns structured JSON plan.
2. Knowledge acquisition: system executes plan queries + mandatory rules context.
3. Review: LLM produces final review report based on plan and acquired knowledge.
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from camel.agents import ChatAgent
from camel.messages import BaseMessage

logger = logging.getLogger(__name__)

_SCOPE_TO_MODE = {
    "product": "explain",
    "test": "test_review",
    "command": "config",
}

_DEFAULT_REVIEW_DIMENSIONS = ["功能覆盖", "用例规范性"]


@dataclass
class ReviewPlan:
    """Structured plan generated by planning stage."""

    understanding: str = ""
    scope_analysis: Optional[Dict[str, str]] = None
    knowledge_queries: List[Dict[str, str]] = field(default_factory=list)
    review_dimensions: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "understanding": self.understanding,
            "scope_analysis": self.scope_analysis,
            "knowledge_queries": self.knowledge_queries,
            "review_dimensions": self.review_dimensions,
        }


@dataclass
class ReviewResult:
    """Final review result."""

    plan: ReviewPlan
    knowledge: str
    review: str
    elapsed_seconds: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "plan": self.plan.to_dict(),
            "knowledge": self.knowledge,
            "review": self.review,
            "elapsed_seconds": self.elapsed_seconds,
        }


class ReviewPipeline:
    """Two-step autonomous review pipeline."""

    def __init__(self, router, model, product_name: str):
        self.router = router
        self.model = model
        self.product_name = (
            product_name.strip()
            if isinstance(product_name, str) and product_name.strip()
            else "NSAE (InfosecOS) 负载均衡器"
        )

    def run(
        self,
        test_cases_text: str,
        bug_profile: Optional[Dict[str, Any]] = None,
    ) -> ReviewResult:
        if not (test_cases_text or "").strip():
            raise ValueError("test_cases_text cannot be empty")

        started_at = time.time()
        planning_input = self._build_planning_input(test_cases_text, bug_profile)

        plan = self._plan(planning_input, has_change_desc=bool(bug_profile))
        knowledge = self._acquire_knowledge(plan, planning_input)
        review = self._review(test_cases_text, plan, knowledge)

        return ReviewResult(
            plan=plan,
            knowledge=knowledge,
            review=review,
            elapsed_seconds=time.time() - started_at,
        )

    def _build_planning_input(
        self,
        test_cases_text: str,
        bug_profile: Optional[Dict[str, Any]],
    ) -> str:
        parts: List[str] = []

        if bug_profile:
            lines = [
                f"- {k}: {self._to_text(v)}"
                for k, v in bug_profile.items()
                if self._to_text(v)
            ]
            if lines:
                parts.append("[变更描述]\n" + "\n".join(lines))

        parts.append("[测试用例内容]\n" + test_cases_text)
        return "\n\n".join(parts)

    def _plan(self, input_text: str, has_change_desc: bool) -> ReviewPlan:
        agent = ChatAgent(
            system_message=BaseMessage.make_assistant_message(
                role_name="测试评审规划者",
                content=self._build_planning_system_prompt(),
            ),
            model=self.model,
        )

        response = agent.step(
            self._build_planning_user_prompt(input_text, has_change_desc)
        )
        raw_text = response.msgs[0].content if response.msgs else ""

        parsed = self._extract_json(raw_text)
        if not parsed:
            logger.warning("Planning JSON parse failed, fallback to default plan")
            return ReviewPlan(
                understanding="",
                scope_analysis=None,
                knowledge_queries=[],
                review_dimensions=list(_DEFAULT_REVIEW_DIMENSIONS),
            )

        return self._coerce_review_plan(parsed, has_change_desc)

    def _build_planning_system_prompt(self) -> str:
        return (
            f"你是 {self.product_name} 的测试评审专家。\n"
            "你的任务是先做评审规划，而不是直接给出评审结论。\n"
            "请根据输入内容，判断评审范围、是否需要补充知识、以及评审维度。\n"
            "必须输出 JSON，不要输出代码块或额外解释。"
        )

    def _build_planning_user_prompt(self, input_text: str, has_change_desc: bool) -> str:
        scope_instruction = (
            "如果输入包含变更描述（例如缺陷修复或功能开发信息），请输出 scope_analysis 对象，"
            "并区分 in_scope 与 out_of_scope。"
            if has_change_desc
            else "本次没有变更描述，请将 scope_analysis 设为 null。"
        )

        return (
            "请阅读以下输入，输出评审计划 JSON。\n"
            f"{scope_instruction}\n"
            "你可以自主决定是否需要额外知识检索。"
            "如果不需要，请将 knowledge_queries 返回空数组。\n\n"
            "JSON 结构如下：\n"
            "{\n"
            "  \"understanding\": \"...\",\n"
            "  \"scope_analysis\": {\n"
            "    \"change_summary\": \"...\",\n"
            "    \"in_scope\": \"...\",\n"
            "    \"out_of_scope\": \"...\",\n"
            "    \"scope_rationale\": \"...\"\n"
            "  } | null,\n"
            "  \"knowledge_queries\": [\n"
            "    {\"query\": \"...\", \"scope\": \"product|test|command\", \"reason\": \"...\"}\n"
            "  ],\n"
            "  \"review_dimensions\": [\"...\"]\n"
            "}\n\n"
            "[输入]\n"
            f"{input_text}"
        )

    def _coerce_review_plan(
        self,
        data: Dict[str, Any],
        has_change_desc: bool,
    ) -> ReviewPlan:
        understanding = self._to_text(data.get("understanding"))
        scope_analysis = self._coerce_scope_analysis(
            data.get("scope_analysis"), has_change_desc
        )
        knowledge_queries = self._coerce_knowledge_queries(
            data.get("knowledge_queries")
        )
        review_dimensions = self._coerce_review_dimensions(
            data.get("review_dimensions")
        )

        return ReviewPlan(
            understanding=understanding,
            scope_analysis=scope_analysis,
            knowledge_queries=knowledge_queries,
            review_dimensions=review_dimensions,
        )

    def _coerce_scope_analysis(
        self,
        raw_scope: Any,
        has_change_desc: bool,
    ) -> Optional[Dict[str, str]]:
        if not has_change_desc:
            return None
        if not isinstance(raw_scope, dict):
            return None

        scope_analysis = {
            "change_summary": self._to_text(raw_scope.get("change_summary")),
            "in_scope": self._to_text(raw_scope.get("in_scope")),
            "out_of_scope": self._to_text(raw_scope.get("out_of_scope")),
            "scope_rationale": self._to_text(raw_scope.get("scope_rationale")),
        }

        if any(scope_analysis.values()):
            return scope_analysis
        return None

    def _coerce_knowledge_queries(self, raw_queries: Any) -> List[Dict[str, str]]:
        if not isinstance(raw_queries, list):
            return []

        normalized: List[Dict[str, str]] = []
        for item in raw_queries:
            if not isinstance(item, dict):
                continue

            query = self._to_text(item.get("query"))
            if not query:
                continue

            scope = self._normalize_scope(item.get("scope"))
            reason = self._to_text(item.get("reason"))

            normalized.append({
                "query": query,
                "scope": scope,
                "reason": reason,
            })

        return normalized

    def _coerce_review_dimensions(self, raw_dimensions: Any) -> List[str]:
        dimensions: List[str] = []

        if isinstance(raw_dimensions, list):
            for item in raw_dimensions:
                text = self._to_text(item)
                if text and text not in dimensions:
                    dimensions.append(text)
        elif isinstance(raw_dimensions, str):
            text = self._to_text(raw_dimensions)
            if text:
                dimensions.append(text)

        if not dimensions:
            return list(_DEFAULT_REVIEW_DIMENSIONS)
        return dimensions

    def _acquire_knowledge(self, plan: ReviewPlan, input_text: str) -> str:
        sections: List[str] = []

        requested = self._retrieve_requested_knowledge(plan)
        if requested:
            sections.append("[LLM 请求的额外知识]\n" + requested)

        mandatory = self._retrieve_mandatory_rules_and_tests(input_text)
        if mandatory:
            sections.append(mandatory)

        return "\n\n---\n\n".join(s for s in sections if s.strip())

    def _retrieve_requested_knowledge(self, plan: ReviewPlan) -> str:
        if not plan.knowledge_queries:
            return ""

        chunks: List[str] = []
        for idx, item in enumerate(plan.knowledge_queries, start=1):
            query = self._to_text(item.get("query"))
            scope = self._normalize_scope(item.get("scope"))
            reason = self._to_text(item.get("reason"))
            mode = _SCOPE_TO_MODE.get(scope, "explain")

            if not query:
                continue

            try:
                retrieval = self.router.retrieve(
                    query=query,
                    mode=mode,
                    max_context_chars=5000,
                )
            except Exception as exc:
                logger.warning(
                    "Knowledge retrieval failed for query '%s': %s",
                    query,
                    exc,
                )
                continue

            context = self._to_text((retrieval or {}).get("context"))
            if not context:
                continue

            header = [
                f"### Query {idx}",
                f"- scope: {scope}",
                f"- mode: {mode}",
                f"- query: {query}",
            ]
            if reason:
                header.append(f"- reason: {reason}")

            chunks.append("\n".join(header) + "\n\n" + context)

        return "\n\n".join(chunks)

    def _retrieve_mandatory_rules_and_tests(self, input_text: str) -> str:
        rules_engine = getattr(self.router, "rules_engine", None)

        # Fallback to router-level test_review retrieval if rules_engine is not exposed.
        if rules_engine is None:
            logger.warning("router.rules_engine not available, fallback to mode=test_review")
            try:
                retrieval = self.router.retrieve(
                    query=self._summarize_text(input_text),
                    mode="test_review",
                    max_context_chars=4500,
                )
            except Exception as exc:
                logger.warning("Fallback rules retrieval failed: %s", exc)
                return ""

            context = self._to_text((retrieval or {}).get("context"))
            if context:
                return "[测试规范与已有测试参考]\n" + context
            return ""

        sections: List[str] = []

        try:
            rules_context = rules_engine.get_rules_context(purpose="review")
            if rules_context:
                sections.append("[测试规范]\n" + rules_context)
        except Exception as exc:
            logger.warning("get_rules_context failed: %s", exc)

        try:
            similar_tests = rules_engine.search_similar_tests(
                query=self._summarize_text(input_text, limit=500),
                max_results=5,
            )
            if similar_tests:
                similar_text = rules_engine.format_similar_tests(
                    similar_tests,
                    max_chars=2600,
                )
                sections.append("[已有测试参考]\n" + similar_text)
        except Exception as exc:
            logger.warning("search_similar_tests failed: %s", exc)

        return "\n\n".join(sections)

    def _review(self, input_text: str, plan: ReviewPlan, knowledge: str) -> str:
        agent = ChatAgent(
            system_message=BaseMessage.make_assistant_message(
                role_name="测试评审执行者",
                content=self._build_review_system_prompt(plan, knowledge),
            ),
            model=self.model,
        )

        review_prompt = (
            "[待评审测试用例]\n"
            f"{input_text}\n\n"
            "请严格依据系统提示中的评审范围、评审维度与知识背景输出评审报告。"
        )

        response = agent.step(review_prompt)
        return response.msgs[0].content if response.msgs else "评审失败: 无返回"

    def _build_review_system_prompt(self, plan: ReviewPlan, knowledge: str) -> str:
        parts: List[str] = [
            f"你是 {self.product_name} 的测试用例评审专家。",
            "请生成清晰、可执行的评审结论，优先指出风险、缺口与改进建议。",
        ]

        if plan.scope_analysis:
            scope = plan.scope_analysis
            parts.extend(
                [
                    "",
                    f"本次评审聚焦于以下变更: {scope.get('change_summary', '')}",
                    f"评审范围(in_scope): {scope.get('in_scope', '')}",
                    f"可降级处理范围(out_of_scope): {scope.get('out_of_scope', '')}",
                    f"范围依据: {scope.get('scope_rationale', '')}",
                    "对于 in_scope 部分重点评审功能覆盖是否充分；对于 out_of_scope 部分仅做规范性检查。",
                ]
            )
        else:
            parts.extend(
                [
                    "",
                    "本次未提供变更范围，请对全部输入用例执行完整评审（覆盖+规范双维度）。",
                ]
            )

        dimensions = plan.review_dimensions or _DEFAULT_REVIEW_DIMENSIONS
        parts.extend(
            [
                "",
                f"请至少从以下维度进行评审: {'；'.join(dimensions)}",
            ]
        )

        if plan.understanding:
            parts.extend(
                [
                    "",
                    "[前期理解]",
                    plan.understanding,
                ]
            )

        if knowledge:
            parts.extend(
                [
                    "",
                    "[相关产品知识与评审规范]",
                    knowledge,
                ]
            )

        parts.extend(
            [
                "",
                "输出要求:",
                "1. 先给总体结论，再给问题清单与改进建议。",
                "2. 问题描述要具体，避免空泛结论。",
                "3. 如果信息不足，必须明确说明不确定点。",
            ]
        )

        return "\n".join(parts)

    def _extract_json(self, text: str) -> Optional[Dict[str, Any]]:
        if not text:
            return None

        match = re.search(r"\{[\s\S]*\}", text)
        if not match:
            return None

        try:
            parsed = json.loads(match.group(0))
        except json.JSONDecodeError:
            return None

        if isinstance(parsed, dict):
            return parsed
        return None

    def _normalize_scope(self, raw_scope: Any) -> str:
        scope = self._to_text(raw_scope).lower()

        if scope in _SCOPE_TO_MODE:
            return scope

        if scope in {"cli", "cmd", "commandline"}:
            return "command"

        if scope in {"rules", "rule", "case", "review"}:
            return "test"

        return "product"

    def _summarize_text(self, text: str, limit: int = 800) -> str:
        compact = re.sub(r"\s+", " ", text or "").strip()
        if len(compact) <= limit:
            return compact
        return compact[:limit]

    @staticmethod
    def _to_text(value: Any) -> str:
        if value is None:
            return ""
        return str(value).strip()
